### ISSUE TITLE
that.getHitSpan is not a function

### ISSUE THREAD

**Issue by sibaram-sahu** [mherrmann/fullcalendar-rightclick#14]
Not able to right click in the day

**Comment by mherrmann** [comment]
Which version of FullCalendar are you using?

**Comment by marko-hologram** [comment]
I am also having this problem. My team updated to FullCalendar 3.7.0 and noticed this error.

After some investigation I noticed that getHitSpan is removed in 3.5.0 and the last version that has that function is 3.4.0, but we didn't manage to fix the error yet.

**Comment by siarcarse** [comment]
Hello @marko-hologram Could you find a solution to the problem? Today I'm in the same situation.

Regards

**Comment by marko-hologram** [comment]
Hello @siarcarse. 

Well the team I was in decided that we didn't need right click functionality after all so we didn't bother trying to make this work in the end. Sorry I wasn't able to help you.

**Comment by badkuzu** [comment]
Hi everyone,
I'm running into the same issue, and what I've figured out is that the equivalent of getHitSpan function (in 3.4.0 and lower) is getHitFootprint (3.5.0 +). 
If I swap `cell = that.getHitSpan(hit);` to `cell = that.getHitFootprint(hit);` I don't get the "is not a function" error, the dayRightclick callback fires only on agendaDay and agendaWeek views (not on the month view) and the variable "cell" logs to the js console as "undefined".
The "hit" variable provides me complete data on logging to console though.

Anybody there with better js skills that could help me evaluate the problem?

**Comment by badkuzu** [comment]
Update:
Actually it works fine now on agendaDay. The callback fires AND the variable "cell" as well as "hit" provide complete data. 
Well except that the callback variables (date, jsEvent, view) are undefined.

On agendaWeek and month view the "cell" is "undefined".

**Comment by sjacq** [comment]
Hi all,

You can just modify the returned value as follows : 

```
if (fcContainer.length) {
                        // var cell;
                        that.prepareHits();
                        let hit  = that.queryHit(ev.pageX, ev.pageY);
                        let cell = that.getHitFootprint(hit);
                        if (cell)
                            return that[trigger]("dayRightclick", {args: [moment(cell.unzonedRange.startMs), cell.resourceId, ev]});
                    }
```

To handle the event, in the calendar definition:  

```
dayRightclick     : function (start, resourceId, jsEvent) {
// Do stuff
```

Works with version up to 3.9

**Comment by AiCaramba** [comment]
```
if (fcContainer.length) {
                        // var cell;
                        that.prepareHits();
                        let hit  = that.queryHit(ev.pageX, ev.pageY);
                        let cell = hit.component.getSafeHitFootprint(hit);
                        if (cell)
                           return that[trigger]("dayRightclick", {args: [moment(cell.unzonedRange.startMs), cell.resourceId, ev]});
                    }
```
that's works everywhere in lastest version

**Comment by badkuzu** [comment]
Thats great, thank you.
The eventRightclick callback still doesn't give me variables, but still a big improvement.

**Comment by sjacq** [comment]
What variables are you talking about ?

**Comment by badkuzu** [comment]
Well, when I use the eventRightclick callback the function is supposed to give me event, jsEvent, view objects.
They are passed correctly on the dayRightclick callback, but not on the eventRightclick.

**Comment by badkuzu** [comment]
example

`  'eventRightclick' => 'function(event, jsEvent, view) {

    	              console.log("an event has been rightclicked!");

                    console.log(event);

          }'`

event is undefined

(I'm using a laravel extension, that's where the => comes from, its actually js within php)

**Comment by sjacq** [comment]
No, On the right click, you will get [start], [resourceId], [event].

Try this on your DataTable definition.

```
dayRightclick: function (start, resourceId, jsEvent) {
console.log(start);
console.log(resourceId);
console.log(jsEvent);
}
```

**Comment by badkuzu** [comment]
so on dayRightclick wheter I pass (start, resourceId, event) or (event, jsEvent, view) I get the same result:

first argument: moment object containing the start of the event
second argument: undefined
third argument: view data

however, the **eventRightclick** callback still responds with undefined to all three variables, no matter which ones I use

**Comment by sjacq** [comment]
Which fc & scheduler version version are you using ?

**Comment by badkuzu** [comment]
I'm not using scheduler at all, and my fc version is 3.8.2

**Comment by sjacq** [comment]
If the last 2 variables are null, then it means your view is not a resource view. You need to make sure you set "GroupByResource"

```
Today: {
   type: "agenda",
   duration: {days: 1},
   groupByDateAndResource: true
}
```

**Comment by badkuzu** [comment]
oooh, so it's meant to give me data about the resource view, and that's only in the scheduler plugin, right?
Is there any way I can just get (event, jsEvent, view) of the event I'm clicking on on a "month" / "agendaWeek" / "agendaDay" view?

**Comment by sjacq** [comment]
No resourceId without the scheduler indeed. 

That plugin was designed to handle right click on empty slots, not on an existing event in the calendar (there are other solutions for that with the eventClick function). So without the scheduler, the only valuable information is the start time of the empty slot you right-click on.

What are you trying to achieve exactly ?

**Comment by badkuzu** [comment]
I see. Well I have a popup menu that enables me to do various things with the events and day slots / cells. So I would love the right click callback to give me an "event" object when I rightclick an event, that would really help me. 
For now I'm using the built-in mouseoverevent callback of the fc, and it's a pretty good hack.

**Comment by sjacq** [comment]
Don't use the dayRightClick.js for this; This was written to handle slots right-click. 

For right-click on an existing event, you can do

```
$(document).on("contextmenu", ".fc-event",  function (e) {
   e.preventDefault();
   // Do your stuff like menu pop-up
 });

The normal click (left) on an event is handled natively with eventClick in the calendar definition.

**Comment by AiCaramba** [comment]
```
(function($) {
    function monkeyPatchViewClass(View) {
        View = View.class || View;
        var renderFn = "render" in View.prototype ? "render" : "renderDates";
        var originalRender = View.prototype[renderFn];
        View.prototype[renderFn] = function() {
            originalRender.call(this);
            if (!this.el.data("fullcalendar-rightclick")) {
                this.registerRightclickListener();
                this.el.data("fullcalendar-rightclick", true);
            }
        };
        View.prototype.registerRightclickListener = function() {
            var that = this;
            // FullCalendar > 3.0.1:
            var trigger = typeof that.publiclyTrigger === "function" ? "publiclyTrigger" : "trigger";
            this.el.on("contextmenu", function(ev) {
                var eventElt = $(ev.target).closest(".fc-event");
                if (eventElt.length) {
                    var seg = eventElt.data("fc-seg");
                    return that[trigger]("eventRightclick", { args: [moment(seg.startMs), seg, ev] });
                } else {
                    // Users of this library may add custom content inside
                    // FullCalendar's DOM structure, eg. popovers. We don't want
                    // to catch rightclicks on these custom elements, so we
                    // check that the clicked element actually lies inside one
                    // of FullCalendars default containers:
                    var fcContainer = $(ev.target).closest(
                        ".fc-bg, .fc-slats, .fc-content-skeleton, " +
                        ".fc-bgevent-skeleton, .fc-highlight-skeleton"
                    );
                    if (fcContainer.length) {
                        // var cell;
                        that.prepareHits();
                        let hit = that.queryHit(ev.pageX, ev.pageY);
                        let cell = hit.component.getSafeHitFootprint(hit);
                        if (cell)
                            return that[trigger]("dayRightclick", {args: [moment(cell.unzonedRange.startMs), ev, that.calendar.getView()]});
                    }
                }
            });
        };
    }

    var fc = $.fullCalendar;
    monkeyPatchViewClass(fc.views.agenda);
    monkeyPatchViewClass(fc.views.basic);
})(jQuery);
```
this is my version. i get all arguments how in left click

**Comment by sjacq** [comment]
Is that a question AiCaramba ?

**Comment by AiCaramba** [comment]
sjacq, no. i just posted my version of plugin. how i understaund, gudzowski have a problems with right click

**Comment by sjacq** [comment]
Yeah but he's not using scheduler and clicks on a calendar event.

**Comment by badkuzu** [comment]
@AiCaramba thank you so much! I'm trying your version now. 

The dayRightclick gives me perfect arguments right now - I get moment object containing the clicked time, a jsEvent object and a view object.
The eventRightclick gives me the same three variables, but... the moment object (1st argument) contains the current time instead of the time of the event. (so 16:56 5 may 2018 CEST at the time of writing the post).
Do you know how to change that? Looks like a minor fix.

Or in the best case scenario, do you know how to make the first argument give me a complete event object with a start / end / isAllDay / id etc. data ???

**Comment by robindv** [comment]
@gudzowski just replace the first argument with `seg.footprint.getEventLegacy()` at line 21:
`return that[trigger]("eventRightclick", { args: [seg.footprint.getEventLegacy(), seg, ev] });`

BTW, I also added an `ev.preventDefault();` after `this.el.on("contextmenu", function(ev) {` to prevent the default context menu from loading.

Good luck!

**Comment by mherrmann** [comment]
Hey all, library author here. Would anybody care to submit a Pull Request that incorporates the above changes (_and_ doesn't break on earlier versions of FullCalendar)?

**Comment by sjacq** [comment]
Hi mhermann, 
I think AiCarambo should do it, it made additional  changes to my original suggestions.

**Comment by GGaritaJ** [comment]
if (fcContainer.length) {
                           that.prepareHits();
                           let hit = that.queryHit(ev.pageX, ev.pageY);
                           let cell = hit.component.getSafeHitFootprint(hit);
                           if (cell)
                               return that[trigger]("dayRightclick", { args: [moment(cell.unzonedRange.startMs), ev, that.calendar.getView()] });
                    }

this code works to me!!! thanks!

**Comment by federico-66** [comment]
I'm not expert in js, but I noticed that `that.prepareHits()` does not produce anything because it refers to the generic `DateComponent`, and if I scroll down and select another cell, I'm getting a wrong date; so I modified the script by invoking the method related to the used grid (`timeGrid` or `dayGrid`).
I also used `footprintToDateProfile` for the conversion of datetime.
This is my version of monkey patch and seems that works well.
I hope that someone more experienced can verify it and eventually improve it.
Sorry for my english :-)

```javascript
/* Based on: https://github.com/mherrmann/fullcalendar-rightclick */
(function ($) {
  function monkeyPatchViewClass(View) {
    View = View.class || View;
    var renderFn = "render" in View.prototype ? "render" : "renderDates";
    var originalRender = View.prototype[renderFn];
    View.prototype[renderFn] = function () {
      originalRender.call(this);
      if (!this.el.data("fullcalendar-rightclick")) {
        this.registerRightclickListener();
        this.el.data("fullcalendar-rightclick", true);
      }
    };
    View.prototype.registerRightclickListener = function () {
      var that = this;
      var grid = this;
      if (that.timeGrid) {
        grid = that.timeGrid;
      } else if (that.dayGrid) {
        grid = that.dayGrid;
      }
      var trigger = typeof that.publiclyTrigger === "function" ? "publiclyTrigger" : "trigger";
      this.el.on("contextmenu", function (ev) {
        ev.preventDefault();
        var eventElt = $(ev.target).closest(".fc-event, .fc-list-item");
        if (eventElt.length) {
          var seg = eventElt.data("fc-seg");
          return that[trigger]("eventRightClick", { args: [seg.footprint.getEventLegacy(), ev, that.calendar.getView()] });
        } else {
          var fcContainer = $(ev.target).closest(
              ".fc-bg, .fc-slats, .fc-content-skeleton, " +
              ".fc-bgevent-skeleton, .fc-highlight-skeleton"
          );
          if (fcContainer.length) {
            grid.prepareHits();
            let hit = grid.queryHit(ev.pageX, ev.pageY);
            if (hit) { 
              let cell = grid.getSafeHitFootprint(hit);
              if (cell) {
                var dateProfile = that.calendar.footprintToDateProfile(cell);
                cell.start = dateProfile.start;
                cell.end = dateProfile.end;
                return that[trigger]("dayRightClick", { args: [cell, ev, that.calendar.getView()] });
              } else {
                //Only for test
                var fcTime = $(ev.target).closest('.fc-time');
                if (fcTime.length)
                  return that[trigger]("timeRightClick", { args: [null, ev, that.calendar.getView()] });
              }
            }
          }
        }
      });
    };
  }

  var fc = $.fullCalendar;
  //monkeyPatchViewClass(fc.views.list);
  monkeyPatchViewClass(fc.views.agenda);
  monkeyPatchViewClass(fc.views.basic);
})(jQuery);
```

**Comment by duckbrain** [comment]
#19 Should have fixed this!
